version: '3'
services:
    web-server:
        image: "nginx:latest"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src/app:/var/www/html
        networks:
            - testtask
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: ./containers/php/Dockerfile
        volumes:
            - ./src/app:/var/www/html
        networks:
            - testtask
        ports:
            - "9090:9000"
        links:
            - mysql-server
    composer:
        image: "composer"
        volumes:
            - "./src/app:/app"
        command: install
    mysql-server:
        image: mysql:latest
        restart: always
        networks:
            - testtask
        environment:
            - MYSQL_DATABASE=school
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - "33306:3306"
        volumes:
            - "./src/db:/var/lib/mysql"

networks:
  testtask:
    driver: bridge
