version: '3'
services:
    web-server:
        image: "nginx:latest"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - testtask
        ports:
            - "8080:80"
        depends_on:
            - php-fpm
    php-fpm:
        image: "php:7.2-fpm"
        volumes:
            - ./src/app:/var/www/html
        networks:
            - testtask
        ports:
            - "9000:9000"
    composer:
        image: "composer"
        volumes:
            - "./src/app:/app"
        command: install
    mysql-server:
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_DATABASE=school
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123456
        ports:
            - "3306:3306"
        volumes:
            - "./src/db:/var/lib/mysql"
networks:
  testtask:
    driver: bridge
